version: 2
updates:
  - package-ecosystem: npm
    directory: /chat2db-community-client
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
      npm-non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /chat2db-community-server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      maven-security:
        applies-to: security-updates
        patterns:
          - "*"
      maven-non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      codeql-actions:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
      actions-non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
